version: '3.5'

networks:
  backend:

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  redis:
    image: redis
    networks:
      - backend
    restart: unless-stopped

  backend-service:
    image: backend
    networks:
      - backend
    volumes:
      - ./logs.txt:/usr/local/frontend/logs.txt
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
