version: '3.5'

networks:
  frontend:
  backend:

services:
  reverse-proxy:
    image: nginx
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: frontend
    networks:
      - frontend
    ports:
      - 5000
    environment:
      - API_URL=http://localhost:8000

  redis:
    image: redis
    networks:
      - backend

  backend:
    image: backend
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./logs.txt:/usr/local/frontend/logs.txt
    ports:
      - 8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_NAME=postgres
      - DB_HOST=db

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    container_name: db
